language: node_js
sudo: required
dist: trusty
addons:
  firefox: '46.0'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js: 6
before_script:
  - npm install -g bower polymer-cli
  - bower install
script:
  - polymer lint --no-follow-dependencies
  - polymer build
  - xvfb-run polymer test
